---

- name: Open Firewall ports to enable docker container connect to host all ports
  shell: iptables -A INPUT -i docker0 -j ACCEPT

- name: Resolve the insconsistent of git on host and virtual machine - 1
  shell: git config --global core.filemode false

- name: Resolve the insconsistent of git on host and virtual machine - 2
  shell: git config --global core.ignorecase false

- name: Install jq
  apt: name={{ item }} state=installed
  with_items:
  - jq
